// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLWUFqdrWXYBFIqvoI08yQqHJyPpG-dE',
    appId: '1:220707437121:web:1fe222abe9c70d2e15e4c0',
    messagingSenderId: '220707437121',
    projectId: 'geostashr',
    authDomain: 'geostashr.firebaseapp.com',
    storageBucket: 'geostashr.appspot.com',
    measurementId: 'G-JEFSFRXRFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARFsWD6MRxOiMfi5GJBnLxftmNdye0tek',
    appId: '1:220707437121:android:85829026618494c815e4c0',
    messagingSenderId: '220707437121',
    projectId: 'geostashr',
    storageBucket: 'geostashr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wXP5xrn8fskvwBN9QyTGXzkcLMkMICM',
    appId: '1:220707437121:ios:9f119a5531c3bff215e4c0',
    messagingSenderId: '220707437121',
    projectId: 'geostashr',
    storageBucket: 'geostashr.appspot.com',
    iosClientId: '220707437121-jebnk9fsg4sjpiltj0dvo2t0akh60rv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6wXP5xrn8fskvwBN9QyTGXzkcLMkMICM',
    appId: '1:220707437121:ios:9f119a5531c3bff215e4c0',
    messagingSenderId: '220707437121',
    projectId: 'geostashr',
    storageBucket: 'geostashr.appspot.com',
    iosClientId: '220707437121-jebnk9fsg4sjpiltj0dvo2t0akh60rv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
